### PR TITLE
[Compilers] C projects should use C flags rather than CXX flags

### PR DESCRIPTION
**Pull request by SuperOptimizer**
In CMAKE, the `*CXX*` flags are for C++ only, so C files are not compiled with anything that falls under `CXX` flags. `C` flags should be used for `.c` files.

### CODE REVIEW

**Review by FintasticMan — COMMENTED** [review]
I think it should use `CMAKE_C_FLAGS*` rather than `CMAKE_CC_FLAGS*`, see https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html.

**Comment by SuperOptimizer** [comment]
> I think it should use `CMAKE_C_FLAGS*` rather than `CMAKE_CC_FLAGS*`, see https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html.

Huh, I could have sworn that Cmake used CCFLAGS. Maybe I'm thinking of normal make? Thanks for the tip, will fix

**Comment by nicbarker** [comment]
Just waiting on the build then we can get this in 👍

**Comment by nicbarker** [comment]
Looking good! 👍

**Pull request merged**
